# 📘Домашнє завдання №9 Описовий аналіз даних (Exploratory Data Analysis)

Виконав: **Bohdan Pinchuk**

Link: https://github.com/BogdanPinchuk/DataScience-PBY_HW9

Використати вбудований датасет:

In [6]:
# Download data (to cover the case when the data aren't accessible)

# !pip install --upgrade nbformat

import shutil
import sqlite3
import pandas as pd
import seaborn as sns
from pathlib import Path
from IPython.display import display

# Input data
ds_name = "iris"
db_file_name = "store_hw9.db"
git_project_url = "https://github.com/BogdanPinchuk/DataScience-PBY_HW9.git"
main_file_name = "Bohdan_Pinchuk_DS_HW9.ipynb"

# Solution

# Note: to handle error: "SSL: CERTIFICATE_VERIFY_FAILED" or no connection to the server
try:
    # for testing
    # raise Exception
    ds_data = sns.load_dataset(ds_name)

    # Use only one time to initialize/update data (at first time)
    # conn = sqlite3.connect(db_file_name)
    # ds_data.to_sql(ds_name, conn, if_exists="replace", index=False)
    # conn.close()
except Exception:
    file_path = Path(db_file_name)

    if not file_path.exists():
        # upload all files
        current_path = !pwd
        current_path = current_path[0]
        parent_path = !dirname "$current_path"
        parent_path = parent_path[0]
        temp_path = f"{parent_path}/temp"

        # Clone data
        !rm -rf "$temp_path"
        !git clone "$git_project_url" "$temp_path"

        source = Path(temp_path)
        destination = Path(current_path)
        exclude = {main_file_name, ".git", ".idea"}

        for item in source.iterdir():
            if item.name in exclude:
                continue

            target = destination / item.name
            if item.is_dir():
                shutil.copytree(item, target, dirs_exist_ok=True)
            else:
                shutil.copy2(item, target)

        # Clean temp folder
        !rm -rf "$temp_path"

    conn = sqlite3.connect(db_file_name)
    ds_data = pd.read_sql(f"SELECT * FROM {ds_name}", conn)
    conn.close()

display(ds_data)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
import seaborn as sns
df = sns.load_dataset('iris')
df.head()

# TODO: change
## Header

# Input data
ages_col_name = "age"
fares_col_name = "fare"

# Solution
iris = ds_data.copy()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Датасет дані про квіти ірисів трьох видів:
* Setosa
* Versicolor
* Virginica

Для кожної квітки виміряно 4 числові характеристики:
* `sepal_length` — довжина чашолистка
* `sepal_width` — ширина чашолистка
* `petal_length` — довжина пелюстки
* `petal_width` — ширина пелюстки

Цільова змінна:
* `species` — вид квітки (категоріальна змінна)

# Завдання (за етапами EDA)
1. Ознайомлення з даними
* Вивести перші 5 рядків
* Визначити:
  * кількість рядків і стовпців
  * назви колонок
  * типи даних
* Питання:
  * Скільки об’єктів у датасеті?
  * Скільки ознак?
2. Розуміння змінних
* Визначити:
  * числові змінні
  * категоріальні змінні
  * Визначити "цільову змінну"
* Питання:
  * Яка змінна є цільовою?
  * Які змінні описують об’єкти?
3. Перевірка пропущених значень
* Перевірити наявність пропусків
* Питання:
  * Чи є пропущені значення?
  * Якщо є — що з ними робити?
4. Описова статистика
* Вивести статистику для числових змінних
* Питання:
  * Яка ознака має найбільше середнє значення?
  * Чи є сильні відмінності між ознаками?
5. Аналіз категоріальних змінних
* Визначити кількість об’єктів кожного класу
* Питання:
  * Чи збалансований датасет (чи класи розподілені приблизно порівну)?
6. Аналіз розподілів
* Побудувати гістограми для всіх числових змінних
* Побудувати boxplot
* Питання:
  * Чи є викиди?
  * Які розподіли (симетричні чи ні)?
7. Аналіз цільової змінної
* Візуалізувати розподіл класів
* Питання:
  * Який клас найчастіший?
8. Біваріантний аналіз
* Побудувати:
  * scatterplot між ознаками
  * boxplot (ознака vs клас)
* Питання:
  * Які ознаки найкраще розділяють класи?
9. Кореляційний аналіз
* Побудувати кореляційну матрицю
* Питання:
  * Які змінні сильно корелюють?
  * Чи є надлишкові ознаки?
10. Зведені таблиці (Pivot Tables)
* Побудувати середні значення ознак по класах
* Питання:
  * Як відрізняються класи між собою?
11. Виявлення закономірностей
* Описати:
  * які ознаки найважливіші
  * як відрізняються класи
12. Висновки
* Написати висновки:
  * про структуру даних
  * про залежност

In [4]:
# testing

import pandas as pd
from IPython.display import display, Markdown

# 1. Створюємо "чорнові" дані вручну (драфт)
data = {
    'petal_length': [1.4, 1.5, 4.5, 5.1],
    'species': ['setosa', 'setosa', 'versicolor', 'virginica']
}
df_draft = pd.DataFrame(data)

# 2. Робимо розрахунки
count = df_draft.shape[0]  # Кількість рядків
avg_petal = df_draft['petal_length'].mean()  # Середнє
unique_species = ", ".join(df_draft['species'].unique())

# 3. Виводимо красиво в Markdown
display(Markdown(f"""
---
### 📋 Звіт (Чернетка)
*   **Кількість об'єктів:** `{count}`
*   **Середня довжина:** {avg_petal:.2f} см
*   **Знайдені види:** *{unique_species}*
---
"""))

---
### 📋 Звіт (Чернетка)
*   **Кількість об'єктів:** `4`
*   **Середня довжина:** 3.12 см
*   **Знайдені види:** *setosa, versicolor, virginica*
---